var multiplexer16 = require('./multiplexer16-def.js');

module.exports = {
        mux4way16: function(
                a1,
                a2,
                a3,
                a4,
                a5,
                a6,
                a7,
                a8,
                a9,
                a10,
                a11,
                a12,
                a13,
                a14,
                a15,
                a16,
                b1,
                b2,
                b3,
                b4,
                b5,
                b6,
                b7,
                b8,
                b9,
                b10,
                b11,
                b12,
                b13,
                b14,
                b15,
                b16,
                c1,
                c2,
                c3,
                c4,
                c5,
                c6,
                c7,
                c8,
                c9,
                c10,
                c11,
                c12,
                c13,
                c14,
                c15,
                c16,
                d1,
                d2,
                d3,
                d4,
                d5,
                d6,
                d7,
                d8,
                d9,
                d10,
                d11,
                d12,
                d13,
                d14,
                d15,
                d16,
                sel1,
                sel2
                ){
            
            var res1 = multiplexer16.multiplexer16(
                        a1,
                        a2,
                        a3,
                        a4,
                        a5,
                        a6,
                        a7,
                        a8,
                        a9,
                        a10,
                        a11,
                        a12,
                        a13,
                        a14,
                        a15,
                        a16,
                        b1,
                        b2,
                        b3,
                        b4,
                        b5,
                        b6,
                        b7,
                        b8,
                        b9,
                        b10,
                        b11,
                        b12,
                        b13,
                        b14,
                        b15,
                        b16,
                        sel1); 
            
            var e1 = res1.r1,
                e2 = res1.r2,
                e3 = res1.r3,
                e4 = res1.r4,
                e5 = res1.r5,
                e6 = res1.r6,
                e7 = res1.r7,
                e8 = res1.r8,
                e9 = res1.r9,
                e10 = res1.r10,
                e11 = res1.r11,
                e12 = res1.r12,
                e13 = res1.r13,
                e14 = res1.r14,
                e15 = res1.r15,
                e16 = res1.r16;
            
            
            var res2 = multiplexer16.multiplexer16(
                        c1,
                        c2,
                        c3,
                        c4,
                        c5,
                        c6,
                        c7,
                        c8,
                        c9,
                        c10,
                        c11,
                        c12,
                        c13,
                        c14,
                        c15,
                        c16,
                        d1,
                        d2,
                        d3,
                        d4,
                        d5,
                        d6,
                        d7,
                        d8,
                        d9,
                        d10,
                        d11,
                        d12,
                        d13,
                        d14,
                        d15,
                        d16,
                        sel1);
        
        var f1 = res2.r1,
                f2 = res2.r2,
                f3 = res2.r3,
                f4 = res2.r4,
                f5 = res2.r5,
                f6 = res2.r6,
                f7 = res2.r7,
                f8 = res2.r8,
                f9 = res2.r9,
                f10 = res2.r10,
                f11 = res2.r11,
                f12 = res2.r12,
                f13 = res2.r13,
                f14 = res2.r14,
                f15 = res2.r15,
                f16 = res2.r16;
            
            
            
            return multiplexer16.multiplexer16(
                        e1,
                        e2,
                        e3,
                        e4,
                        e5,
                        e6,
                        e7,
                        e8,
                        e9,
                        e10,
                        e11,
                        e12,
                        e13,
                        e14,
                        e15,
                        e16,
                        f1,
                        f2,
                        f3,
                        f4,
                        f5,
                        f6,
                        f7,
                        f8,
                        f9,
                        f10,
                        f11,
                        f12,
                        f13,
                        f14,
                        f15,
                        f16,
                        sel2);
           
    }
};

    // IN a[16], b[16], c[16], d[16], sel[2];
    // OUT out[16];
//     	Mux16(a=a,b=b,sel=sel[0],out=q); 
//   	Mux16(a=c,b=d,sel=sel[0],out=r);
// 	Mux16(a=q,b=r,sel=sel[1],out=out);