var multiplexer16 = require('./multiplexer16-def.js');

module.exports = {
        mux4way16: function(
                a1,
                a2,
                a3,
                a4,
                a5,
                a6,
                a7,
                a8,
                a9,
                a10,
                a11,
                a12,
                a13,
                a14,
                a15,
                a16,
                b1,
                b2,
                b3,
                b4,
                b5,
                b6,
                b7,
                b8,
                b9,
                b10,
                b11,
                b12,
                b13,
                b14,
                b15,
                b16,
                c1,
                c2,
                c3,
                c4,
                c5,
                c6,
                c7,
                c8,
                c9,
                c10,
                c11,
                c12,
                c13,
                c14,
                c15,
                c16,
                d1,
                d2,
                d3,
                d4,
                d5,
                d6,
                d7,
                d8,
                d9,
                d10,
                d11,
                d12,
                d13,
                d14,
                d15,
                d16,
                e1,
                e2,
                e3,
                e4,
                e5,
                e6,
                e7,
                e8,
                e9,
                e10,
                e11,
                e12,
                e13,
                e14,
                e15,
                e16,
                f1,
                f2,
                f3,
                f4,
                f5,
                f6,
                f7,
                f8,
                f9,
                f10,
                f11,
                f12,
                f13,
                f14,
                f15,
                f16,
                g1,
                g2,
                g3,
                g4,
                g5,
                g6,
                g7,
                g8,
                g9,
                g10,
                g11,
                g12,
                g13,
                g14,
                g15,
                g16,
                h1,
                h2,
                h3,
                h4,
                h5,
                h6,
                h7,
                h8,
                h9,
                h10,
                h11,
                h12,
                h13,
                h14,
                h15,
                h16,
                sel1,
                sel2,
                sel3
                ){
            
            var res1 = multiplexer16.multiplexer16(
                        a1,
                        a2,
                        a3,
                        a4,
                        a5,
                        a6,
                        a7,
                        a8,
                        a9,
                        a10,
                        a11,
                        a12,
                        a13,
                        a14,
                        a15,
                        a16,
                        b1,
                        b2,
                        b3,
                        b4,
                        b5,
                        b6,
                        b7,
                        b8,
                        b9,
                        b10,
                        b11,
                        b12,
                        b13,
                        b14,
                        b15,
                        b16,
                        sel1); 
            
            var i1 = res1.r1,
                i2 = res1.r2,
                i3 = res1.r3,
                i4 = res1.r4,
                i5 = res1.r5,
                i6 = res1.r6,
                i7 = res1.r7,
                i8 = res1.r8,
                i9 = res1.r9,
                i10 = res1.r10,
                i11 = res1.r11,
                i12 = res1.r12,
                i13 = res1.r13,
                i14 = res1.r14,
                i15 = res1.r15,
                i16 = res1.r16;
            
            
            var res2 = multiplexer16.multiplexer16(
                        c1,
                        c2,
                        c3,
                        c4,
                        c5,
                        c6,
                        c7,
                        c8,
                        c9,
                        c10,
                        c11,
                        c12,
                        c13,
                        c14,
                        c15,
                        c16,
                        d1,
                        d2,
                        d3,
                        d4,
                        d5,
                        d6,
                        d7,
                        d8,
                        d9,
                        d10,
                        d11,
                        d12,
                        d13,
                        d14,
                        d15,
                        d16,
                        sel1);
        
        var j1 = res2.r1,
                j2 = res2.r2,
                j3 = res2.r3,
                j4 = res2.r4,
                j5 = res2.r5,
                j6 = res2.r6,
                j7 = res2.r7,
                j8 = res2.r8,
                j9 = res2.r9,
                j10 = res2.r10,
                j11 = res2.r11,
                j12 = res2.r12,
                j13 = res2.r13,
                j14 = res2.r14,
                j15 = res2.r15,
                j16 = res2.r16;
            
            var res3 = multiplexer16.multiplexer16(
                        e1,
                        e2,
                        e3,
                        e4,
                        e5,
                        e6,
                        e7,
                        e8,
                        e9,
                        e10,
                        e11,
                        e12,
                        e13,
                        e14,
                        e15,
                        e16,
                        f1,
                        f2,
                        f3,
                        f4,
                        f5,
                        f6,
                        f7,
                        f8,
                        f9,
                        f10,
                        f11,
                        f12,
                        f13,
                        f14,
                        f15,
                        f16,
                        sel1);
        
        var k1 = res3.r1,
                k2 = res3.r2,
                k3 = res3.r3,
                k4 = res3.r4,
                k5 = res3.r5,
                k6 = res3.r6,
                k7 = res3.r7,
                k8 = res3.r8,
                k9 = res3.r9,
                k10 = res3.r10,
                k11 = res3.r11,
                k12 = res3.r12,
                k13 = res3.r13,
                k14 = res3.r14,
                k15 = res3.r15,
                k16 = res3.r16;
                
        var res4 = multiplexer16.multiplexer16(
                        g1,
                        g2,
                        g3,
                        g4,
                        g5,
                        g6,
                        g7,
                        g8,
                        g9,
                        g10,
                        g11,
                        g12,
                        g13,
                        g14,
                        g15,
                        g16,
                        h1,
                        h2,
                        h3,
                        h4,
                        h5,
                        h6,
                        h7,
                        h8,
                        h9,
                        h10,
                        h11,
                        h12,
                        h13,
                        h14,
                        h15,
                        h16,
                        sel1);
        
        var l1 = res4.r1,
                l2 = res4.r2,
                l3 = res4.r3,
                l4 = res4.r4,
                l5 = res4.r5,
                l6 = res4.r6,
                l7 = res4.r7,
                l8 = res4.r8,
                l9 = res4.r9,
                l10 = res4.r10,
                l11 = res4.r11,
                l12 = res4.r12,
                l13 = res4.r13,
                l14 = res4.r14,
                l15 = res4.r15,
                l16 = res4.r16;
                
                
        var res5 = multiplexer16.multiplexer16(
                        i1,
                        i2,
                        i3,
                        i4,
                        i5,
                        i6,
                        i7,
                        i8,
                        i9,
                        i10,
                        i11,
                        i12,
                        i13,
                        i14,
                        i15,
                        i16,
                        j1,
                        j2,
                        j3,
                        j4,
                        j5,
                        j6,
                        j7,
                        j8,
                        j9,
                        j10,
                        j11,
                        j12,
                        j13,
                        j14,
                        j15,
                        j16,
                        sel2);
        
        var m1 = res5.r1,
                m2 = res5.r2,
                m3 = res5.r3,
                m4 = res5.r4,
                m5 = res5.r5,
                m6 = res5.r6,
                m7 = res5.r7,
                m8 = res5.r8,
                m9 = res5.r9,
                m10 = res5.r10,
                m11 = res5.r11,
                m12 = res5.r12,
                m13 = res5.r13,
                m14 = res5.r14,
                m15 = res5.r15,
                m16 = res5.r16;
                
        var res6 = multiplexer16.multiplexer16(
                        k1,
                        k2,
                        k3,
                        k4,
                        k5,
                        k6,
                        k7,
                        k8,
                        k9,
                        k10,
                        k11,
                        k12,
                        k13,
                        k14,
                        k15,
                        k16,
                        l1,
                        l2,
                        l3,
                        l4,
                        l5,
                        l6,
                        l7,
                        l8,
                        l9,
                        l10,
                        l11,
                        l12,
                        l13,
                        l14,
                        l15,
                        l16,
                        sel2);
        
        var n1 = res6.r1,
                n2 = res6.r2,
                n3 = res6.r3,
                n4 = res6.r4,
                n5 = res6.r5,
                n6 = res6.r6,
                n7 = res6.r7,
                n8 = res6.r8,
                n9 = res6.r9,
                n10 = res6.r10,
                n11 = res6.r11,
                n12 = res6.r12,
                n13 = res6.r13,
                n14 = res6.r14,
                n15 = res6.r15,
                n16 = res6.r16;
            
        return multiplexer16.multiplexer16(
                        m1,
                        m2,
                        m3,
                        m4,
                        m5,
                        m6,
                        m7,
                        m8,
                        m9,
                        m10,
                        m11,
                        m12,
                        m13,
                        m14,
                        m15,
                        m16,
                        n1,
                        n2,
                        n3,
                        n4,
                        n5,
                        n6,
                        n7,
                        n8,
                        n9,
                        n10,
                        n11,
                        n12,
                        n13,
                        n14,
                        n15,
                        n16,
                        sel3);
           
    }
};

// CHIP Mux8Way16 {
//     IN a[16], b[16], c[16], d[16],
//       e[16], f[16], g[16], h[16],
//       sel[3];
//     OUT out[16];

//     PARTS:
//     	Mux16(a=a,b=b,sel=sel[0],out=q); 
//   	Mux16(a=c,b=d,sel=sel[0],out=r);
// 	Mux16(a=e,b=f,sel=sel[0],out=s); 
//   	Mux16(a=g,b=h,sel=sel[0],out=t);

// 	Mux16(a=q,b=r,sel=sel[1],out=y);
// 	Mux16(a=s,b=t,sel=sel[1],out=z);

// 	Mux16(a=y,b=z,sel=sel[2],out=out);
// }